version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=novaville
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ton_password_securise
    # VOLUMES DÉSACTIVÉS POUR LE TEST
    networks:
      - novaville-net

  backend:
    image: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/novaville-backend:latest
    container_name: backend
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=novaville
      - DB_USER=postgres
      - DB_PASSWORD=ton_password_securise
      - MIGRATE=1
    depends_on:
      - postgres
    networks:
      - novaville-net

networks:
  novaville-net:
    driver: bridge
