version: '3.8'

services:
  # --- BASE DE DONNÉES ---
  postgres:
    image: novaville.azurecr.io/bitnami-postgresql:15
    container_name: postgres
    user: root 
    environment:
      - POSTGRESQL_DATABASE=novaville_db
      - POSTGRESQL_USERNAME=novaville_user
      - POSTGRESQL_PASSWORD=YOUR_SECURE_PASSWORD
      - POSTGRESQL_VOLUME_DIR=/bitnami/postgresql
    volumes:
      - db-volume:/bitnami/postgresql/data
    networks:
      - novaville-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novaville_user -d novaville_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- DJANGO BACKEND ---
  backend:
    image: novaville.azurecr.io/novaville-backend:latest
    container_name: backend
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=novaville_db
      - DB_USER=novaville_user
      - DB_PASSWORD=YOUR_SECURE_PASSWORD
      - MIGRATE=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=ChangeMe123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - novaville-net
    restart: always
    # Note : Pas de section 'ports' ici pour éviter les erreurs de routing Azure

  # --- FRONTEND (Point d'entrée) ---
  frontend:
    image: novaville.azurecr.io/novaville-frontend:latest
    container_name: frontend
    ports:
      - "80:80" # C'est le SEUL port exposé vers l'extérieur
    # depends_on:
    #   - backend
    networks:
      - novaville-net
    restart: always

networks:
  novaville-net:
    driver: bridge

volumes:
  db-volume: