# Generated by Django 5.2.11 on 2026-02-22 21:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Neighborhood name', max_length=255)),
                ('postal_code', models.CharField(help_text='Postal code', max_length=10)),
            ],
            options={
                'verbose_name': 'Neighborhood',
                'verbose_name_plural': 'Neighborhoods',
                'db_table': 'neighborhoods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Theme title', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Event Theme',
                'verbose_name_plural': 'Event Themes',
                'db_table': 'theme_events',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('ELECTED', 'Elected Official'), ('AGENT', 'Municipal Agent'), ('GLOBAL_ADMIN', 'Global Administrator')], default='CITIZEN', help_text='User role in the system', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('neighborhood', models.ForeignKey(blank=True, help_text="User's neighborhood", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.neighborhood')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('ROADS', 'Roads'), ('LIGHTING', 'Lighting'), ('CLEANLINESS', 'Cleanliness')], help_text='Type of problem reported', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Report creation date')),
                ('status', models.CharField(choices=[('RECORDED', 'Recorded'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='RECORDED', help_text='Current status of the report', max_length=20)),
                ('citizen_target', models.CharField(blank=True, choices=[('CITIZEN', 'Citizen'), ('ELECTED', 'Elected Official'), ('AGENT', 'Municipal Agent'), ('GLOBAL_ADMIN', 'Global Administrator')], help_text='Target role for this report', max_length=20, null=True)),
                ('neighborhood', models.ForeignKey(blank=True, help_text='Neighborhood where the issue was reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.neighborhood')),
                ('user', models.ForeignKey(help_text='User who created the report', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Survey title', max_length=255)),
                ('description', models.TextField(help_text='Survey description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Survey creation date')),
                ('start_date', models.DateTimeField(help_text='Survey start date')),
                ('end_date', models.DateTimeField(help_text='Survey end date')),
                ('created_by', models.ForeignKey(help_text='User who created the survey', on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=255)),
                ('survey', models.ForeignKey(help_text='Survey this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.survey')),
            ],
            options={
                'verbose_name': 'Survey Option',
                'verbose_name_plural': 'Survey Options',
                'db_table': 'survey_options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('description', models.TextField(help_text='Event description')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                ('created_by', models.ForeignKey(help_text='User who created the event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, help_text='Event theme/category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.themeevent')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Vote timestamp')),
                ('option', models.ForeignKey(help_text='Selected option', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.surveyoption')),
                ('survey', models.ForeignKey(help_text='Survey being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.survey')),
                ('user', models.ForeignKey(help_text='User who voted', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'votes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'survey')},
            },
        ),
    ]
