# Generated by Django 5.2.12 on 2026-03-06 16:49

import core.db.models.useful_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useful_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulinfo',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Format: {"Lundi": ["09:00-16:00"], "Mardi": []}', validators=[core.db.models.useful_info.validate_opening_hours]),
        ),
    ]
