# Generated by Django 5.2.12 on 2026-03-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_move_citizen_target_add_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usefulinfo',
            name='x',
            field=models.URLField(blank=True, null=True),
        ),
    ]
