# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_move_citizen_target_add_title'),
    ]

    operations = [
        # 1. Add location fields to Report
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(
                blank=True,
                help_text='Latitude of the reported issue',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(
                blank=True,
                help_text='Longitude of the reported issue',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(
                blank=True,
                help_text='Address or location description',
                max_length=255,
                null=True,
            ),
        ),
        # 2. Create Media model
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File uploaded', upload_to='reports/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Upload date')),
                ('report', models.ForeignKey(help_text='Report this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.report')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
    ]
