# Generated by Django 5.2.12 on 2026-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usefulinfo_facebook_usefulinfo_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usefulinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usefulinfo',
            name='x',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
