# Generated by Django 5.2.14 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login_completed',
            field=models.BooleanField(
                default=False,
                help_text='Whether the user has completed their first login and set their own password',
            ),
        ),
    ]
