name: Network Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  test-reseaux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.3"

      - name: Create .env file for tests
        working-directory: frontend
        run: |
          cat << 'EOF' > .env
          API_BASE_URL=https://example.com
          SOME_KEY=dummy
          EOF

      - name: Pub get
        working-directory: frontend
        run: flutter pub get

      - name: Test api_client
        working-directory: frontend
        run: flutter test test/core/network/api_client_test.dart

      - name: Test authenticated_client
        working-directory: frontend
        run: flutter test test/core/network/authenticated_client_test.dart

      - name: Test authenticated_client_factory
        working-directory: frontend
        run: flutter test test/core/network/authenticated_client_factory_test.dart
