name: Semgrep SAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Scan every Sunday at 00:00
    - cron: '0 0 * * 0'

jobs:
  semgrep:
    name: Security Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config=auto --error --verbose